<a href="https://colab.research.google.com/github/sudheervobili/Pytorch/blob/main/Pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Neural network with single layer**

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out

In [ ]:
features = torch.rand(10,5)
print(features.shape[1])

5


In [ ]:
model = Model(features.shape[1])
model(features)

tensor([[0.3668],
        [0.3113],
        [0.3667],
        [0.3353],
        [0.2848],
        [0.4131],
        [0.3571],
        [0.3773],
        [0.4068],
        [0.3372]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights and bias
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.4301, -0.4243, -0.0153, -0.4007, -0.2762]], requires_grad=True)
Parameter containing:
tensor([0.3659], requires_grad=True)


In [ ]:
! pip install torchinfo

In [ ]:
from torch import nn
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Neural network with Multiple hidden layers**

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,5)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(5,4)
    self.relu = nn.ReLU()
    self.linear3 = nn.Linear(4,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,x):
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.relu(out)
    out = self.linear3(out)
    out = self.sigmoid(out)
    return out

In [ ]:
model1= Model1(features.shape[1])
model1(features)

tensor([[0.5804],
        [0.5910],
        [0.5813],
        [0.5893],
        [0.5815],
        [0.5882],
        [0.5872],
        [0.5807],
        [0.5831],
        [0.5749]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights and bias
print(model1.linear3.weight)
print(model1.linear3.bias)

Parameter containing:
tensor([[-0.1029, -0.0783,  0.3907, -0.3682]], requires_grad=True)
Parameter containing:
tensor([0.3048], requires_grad=True)


In [ ]:
from torch import nn
from torchinfo import summary
summary(model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 5]                   30
├─ReLU: 1-2                              [10, 5]                   --
├─Linear: 1-3                            [10, 4]                   24
├─ReLU: 1-4                              [10, 4]                   --
├─Linear: 1-5                            [10, 1]                   5
├─Sigmoid: 1-6                           [10, 1]                   --
Total params: 59
Trainable params: 59
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
import torch
import torch.nn as nn

class Model3(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(num_features, 5),
            nn.ReLU(),
            nn.Linear(5, 4),
            nn.ReLU(),
            nn.Linear(4, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)


In [ ]:
model3 = Model3(features.shape[1])
model3(features)

tensor([[0.5350],
        [0.5268],
        [0.5239],
        [0.5270],
        [0.5337],
        [0.5216],
        [0.5317],
        [0.5350],
        [0.5237],
        [0.5236]], grad_fn=<SigmoidBackward0>)